site_name: Date Tools
site_url: http://webng.gitlab-pages.paltalk.com/webng/vue-firebase-data/
theme: material

repo_url: http://gitlab.paltalk.com/webng/vue-firebase-data
repo_name: Gitlab

site_dir: public

pages:
  - Home: index.md
  - Usage: usage.md
  - Last Test Results: test.md

markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - footnotes
  - meta
  - toc(permalink=true)
